### PR TITLE
Image size

### PR DESCRIPTION
**Pull request by PiyushRaj927**

### CODE REVIEW

**Comment by PiyushRaj927** [comment]
# a
# a

**Comment by PiyushRaj927** [comment]
# a
# a

**Comment by jayanth-kumar-morem** [comment]
@PiyushRaj927, Minor changes in styling. Also, would like to know whether the full output is sorted by decreasing order of file size.

📊 **Bitnami Image Analysis (Commit: 49b7745)**

**Summary:**
- Total Size: 6.53GB
- Efficiency: 97.4664%
- Wasted Bytes: 250584985 bytes (251 MB)
- User Wasted Percent: 4.0065%

**Inefficient Files:**
| Count | Wasted Space | File Path |
|-------|--------------|-----------|
| 2     | 14 MB        | /opt/bitnami/postgresql/share/contrib/postgis-3.3/spatial_ref_sys.sql |
| 2     | 9.3 MB       | /opt/bitnami/postgresql/lib/postgis-3.so |
| 2     | 8.7 MB       | /usr/lib/x86_64-linux-gnu/perl/5.32.1/CORE/charclass_invlists.h |
| 3     | 7.4 MB       | /usr/lib/x86_64-linux-gnu/libperl.so.5.32.1 |
| 2     | 6.7 MB       | /usr/lib/git-core/git |
| 3     | 6.7 MB       | /usr/bin/git |
| 2     | 5.5 MB       | /usr/lib/x86_64-linux-gnu/perl/5.32.1/auto/Encode/JP/JP.so |
| 2     | 5.0 MB       | /opt/bitnami/postgresql/lib/postgis_raster-3.so |
| 2     | 4.8 MB       | /usr/lib/x86_64-linux-gnu/perl/5.32.1/auto/Encode/KR/KR.so |
| 2     | 4.2 MB       | /usr/lib/x86_64-linux-gnu/perl/5.32.1/auto/Encode/CN/CN.so |

<FULL OUTPUT>

**Comment by PiyushRaj927** [comment]
> Also, would like to know whether the full output is sorted by decreasing order of file size.

It seems that the default order of the output from Dive is based on decreasing size. However, I couldn't find any official documentation confirming this.

**Comment by singhalkarun** [comment]
Hi @PiyushRaj927 Let's focus more on major requirements

1. Current Size
2. Previous Size
3. Reason for the difference (one layer affecting majorily)

Let's abstract out other details from PR to keep it less noisy, we can have a link where I can go to see the detailed analysis.

**Comment by PiyushRaj927** [comment]
> 3\. Reason for the difference (one layer affecting majorily)

Hi @singhalkarun, I need help determining the approach for calculating changes in pull request layers. Reordering of layers makes direct comparison difficult, and the metric mentioned may underreport due to small accumulated changes.

**Pull request closed without merging**
